Areas/SecurityGuard/Models/RegisterViewModel.cs
using LadiesChoice.Models;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace LadiesChoice.Areas.SecurityGuard.ViewModels
{
    public class RegisterViewModel
    {
        public RegisterViewModel() {
            ProfileModel = new ProfileModel();
        }
        public Utilities.Date BirthDate { get; set; }

        public ProfileModel ProfileModel { get; set; }
        
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email address")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [System.Web.Mvc.Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        [Display(Name = "Secret Question")]
        public string SecretQuestion { get; set; }

        [Display(Name = "Secret Answer")]
        public string SecretAnswer { get; set; }

        public bool Approve { get; set; }

        public bool RequireSecretQuestionAndAnswer { get; set; }
    }
}

Controllers/SGAccountController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net.Configuration;
using System.Web.Mvc;
using System.Web.Security;
using LadiesChoice.Mailers;
using LadiesChoice.Mailers.Models;
using SecurityGuard.Core;
using SecurityGuard.Interfaces;
using SecurityGuard.Services;
using SecurityGuard.ViewModels;
using viewModels = LadiesChoice.Areas.SecurityGuard.ViewModels;
using LadiesChoice.Models;
using LadiesChoice.ViewModels;
using WebMatrix.WebData;

namespace LadiesChoice.Controllers
{
    /// <summary>
    /// This class handles all the normal logon, logoff, 
    /// register, change password, and forgot password operations
    /// that occur in the public part of your web application.
    /// </summary>
    public class SGAccountController : BaseController
    {
                
        #region ctors

        private IMembershipService membershipService;
        private IAuthenticationService authenticationService;
        private IFormsAuthenticationService formsAuthenticationService;
        private IPasswordResetMailer _mailer = new PasswordResetMailer();
        private Utilities.DBEntities db = new Utilities.DBEntities(); //added by Paul for adding new profiles

        public SGAccountController()
        {
            this.membershipService = new MembershipService(Membership.Provider);
            this.authenticationService = new AuthenticationService(membershipService, new FormsAuthenticationService());
            this.formsAuthenticationService = new FormsAuthenticationService();
        }

        #endregion

        #region Public Properties

        public IPasswordResetMailer Mailer
        {
            get { return _mailer; }
            set { _mailer = value; }
        }

        #endregion

        public virtual ActionResult Index()
        {
            return View();
        }

        #region LogOn Methods

        [HttpGet]
        public virtual ActionResult Login()
        {
            var viewModel = new LogOnViewModel()
            {
                EnablePasswordReset = membershipService.EnablePasswordReset
            };
            return ContextDependentView(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Login(LogOnViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                //begin Pauls additional email as username check
                string userName;

                if (model.UserName.Contains("@"))
                {
                    userName = Membership.GetUserNameByEmail(model.UserName);
                }
                else
                {
                    userName = model.UserName;
                }
                //end Pauls addition (also a change to the LogOn parameters to use "username"
                
                if (authenticationService.LogOn(userName, model.Password, model.RememberMe))
                {
                    //Pauls additions to set the gender in session
                    var g = (Guid)Membership.GetUser(userName).ProviderUserKey;
                    ProfileModel p = db.ProfileModels.FirstOrDefault(x => x.userID == g);
                    Utilities.SessionHelpers.SaveGenderInSession(this.HttpContext, p.Gender);
                    //end Pauls session stuff

                    if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1 && returnUrl.StartsWith("/")
                        && !returnUrl.StartsWith("//") && !returnUrl.StartsWith("/\\"))
                    {
                        return Redirect(returnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                else
                {
                    MembershipUser user = membershipService.GetUser(model.UserName);
                    if (user == null)
                    {
                        ModelState.AddModelError("", "This account does not exist. Please try again.");
                    }
                    else
                    {
                        if (!user.IsApproved)
                        {
                            ModelState.AddModelError("", "Your account has not been approved yet.");
                        }
                        else if (user.IsLockedOut)
                        {
                            ModelState.AddModelError("", "Your account is currently locked.");
                        }
                        else
                        {
                            ModelState.AddModelError("", "The user name or password provided is incorrect.");
                        }
                    }
                }
            }

            // If we got this far, something failed, redisplay form
            return RedirectToAction("Login");
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        [ValidateAntiForgeryToken()]
        public virtual ActionResult LogOff()
        {
            authenticationService.LogOff();

            return RedirectToAction("Index", "Home");
        } 
        #endregion

        #region Register Methods

        //public virtual ActionResult Register()
        //{
        //    var model = new viewModels.RegisterViewModel()
        //    {
        //        RequireSecretQuestionAndAnswer = membershipService.RequiresQuestionAndAnswer
        //    };
        //    return ContextDependentView(model);
        //}

        public virtual ActionResult Register()
        {
            var model = new RegisterProfileViewModel();
            
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public virtual ActionResult Register(RegisterProfileViewModel model)
        {
            model.BirthDate.Day = model.Day;
            model.BirthDate.Month = model.Month;
            model.BirthDate.Year = model.Year;
            
            if (ModelState.IsValid)
            {
                
                
                // Attempt to register the user
                MembershipCreateStatus createStatus;
                //membershipService.CreateUser(model.UserName, model.Password, model.Email, model.SecretQuestion, model.SecretAnswer, true, out createStatus);
                membershipService.CreateUser(model.UserName, model.Password, model.Email, null, null, true, out createStatus);

                if (createStatus == MembershipCreateStatus.Success)
                {
                    formsAuthenticationService.SetAuthCookie(model.UserName, false /* createPersistentCookie */);
                    //return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", ErrorCodeToString(createStatus));
                }
                //Paul's addition for saving the gender and birthdate to a new profile
                try
                {
                    //Utilities.Date birthdate = new Utilities.Date();
                    //birthdate.Day = model.
                    //model.ProfileModel.BirthDate = 
                    ProfileModel p = new ProfileModel();
                    //p.userID = WebSecurity.CurrentUserId;
                    MembershipUser user = Membership.GetUser(model.UserName);
                    p.userID = (Guid)user.ProviderUserKey;
                    p.Gender = model.Gender;
                    this.HttpContext.Session["gender"] = model.Gender;
                    p.BirthDate = (DateTime)model.BirthDate.DateTime;
                    db.ProfileModels.Add(p);
                    db.SaveChanges();
                    return RedirectToAction("EditProfile", "Profile");
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                }
                //end Paul's addition
            }

            return RedirectToAction("Register");
        }


        #endregion

        #region ChangePassword Methods
        
        /// <summary>
        /// This allows the logged on user to change his password.
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public virtual ActionResult ChangePassword()
        {
            var viewModel = new ChangePasswordViewModel();

            return View(viewModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public virtual ActionResult ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {

                // ChangePassword will throw an exception rather
                // than return false in certain failure scenarios.
                bool changePasswordSucceeded;
                try
                {
                    MembershipUser currentUser = Membership.GetUser(User.Identity.Name, true /* userIsOnline */);
                    changePasswordSucceeded = currentUser.ChangePassword(model.OldPassword, model.NewPassword);
                }
                catch (Exception)
                {
                    changePasswordSucceeded = false;
                }

                if (changePasswordSucceeded)
                {
                    return RedirectToAction("ChangePasswordSuccess");
                }
                else
                {
                    ModelState.AddModelError("", "The current password is incorrect or the new password is invalid.");
                }
            }

            // If we got this far, something failed, redisplay form
            return RedirectToAction("ChangePassword");
        }

        //
        // GET: /Account/ChangePasswordSuccess

        public virtual ActionResult ChangePasswordSuccess()
        {
            return View();
        }


        #endregion

        #region Forgot Password Methods

Views/SGAccount/Register.cshtml
@model LadiesChoice.ViewModels.RegisterProfileViewModel
@{
    ViewBag.Title = "Register";
}
<div class="row-fluid">
       <div class="span6">
    <h2>Register now!</h2>
<script src="@Url.Content("~/Content/SecurityGuard/scripts/jquery-1.6.1.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Content/SecurityGuard/scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Content/SecurityGuard/scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Content/SecurityGuard/scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm((string)ViewBag.FormAction, "SGAccount",FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

        <fieldset>
            <legend>Account Information</legend>
            <div class="control-group">
                @Html.LabelFor(model => model.Gender, new {@class="control-label"})
                @Html.DropDownListFor(model => model.Gender, Model.GenderList, new {@class="controls"})
                @Html.ValidationMessageFor(model => model.Gender) 
            </div>
            <div class="control-group">
                @Html.LabelFor(m => m.BirthDate, new {@class="control-label"})
               @* @Html.Partial("DateSelector_DropdownList")*@
                <div class="controls controls-row">
                @Html.DropDownListFor(model => model.Year, Model.YearList, new {@class="span3"})
                @Html.DropDownListFor(model => model.Month, Model.MonthList, new {@class="span4"})
                @Html.DropDownListFor(model => model.Day, Model.DayList, new {@class="span3"})
                @Html.ValidationMessageFor(model => model.BirthDate)
                </div>           
            </div>
            <div class="control-group">
                @Html.LabelFor(m => m.UserName, new {@class="control-label"})
                @Html.TextBoxFor(m => m.UserName, new {@class="controls"})
                @Html.ValidationMessageFor(m => m.UserName)
            </div>
            <div class="control-group">
                @Html.LabelFor(m => m.Email, new {@class="control-label"})
                @Html.TextBoxFor(m => m.Email, new {@class="controls"})
                @Html.ValidationMessageFor(m => m.Email)
            </div>           
            <div class="control-group">
                @Html.LabelFor(m => m.EmailAgain, new {@class="control-label"})
                @Html.TextBoxFor(m => m.EmailAgain, new {@class="controls"})
                @Html.ValidationMessageFor(m => m.EmailAgain)
            </div>
            <div class="control-group">
                @Html.LabelFor(m => m.Password, new {@class="control-label"})
                @Html.PasswordFor(m => m.Password, new {@class="controls"})
                @Html.ValidationMessageFor(m => m.Password)
            </div>
          <div class="control-group">
              <div class="controls">
                <input type="submit" value="Create My Profile" />
                <p>
                  <small>
                    By creating a profile you agree to our <a href="/terms-and-conditions">Terms and Conditions &amp; Privacy Policy</a>
                  </small>
                </p>
              </div>
            </div>
        </fieldset>
    }
    </div>
     @Html.Partial("ReasonsToChoosePartial")
      </div>