ViewModels/MyPhotosViewModel.cs
using LadiesChoice.Utilities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Linq;
using System.Web;

namespace LadiesChoice.ViewModels
{
    public class MyPhotosViewModel : CommonViewModel
    {
        
        public Guid PhotoModelID;
        public string PhotoPath { get { return ConfigurationManager.AppSettings.Get("PhotoPath"); } }
        //[Required]
        //[DataType(DataType.Upload)]

        [Display(Name = "Add a photo")]
        [ValidateFile(ErrorMessage = "Please select a JPG or PNG image smaller than 3MB")]
        public HttpPostedFileBase File { get; set; }
        public string Caption { get; set; }

        public IEnumerable<Models.PhotoModel> Photos { get; set; }
       
        public string UsernameOfPhotoOwner { get; set; }

        public bool IsIPhoneOrIpad { get; set; }
        public Guid ProfileModelID { get; set; }
        public MyPhotosViewModel() {
            
        }

        public MyPhotosViewModel(Guid profileModelID, DBEntities db) {
            
            var userInfo = from pf in db.ProfileModels
                              join ur in db.UserProfiles on pf.iUserID equals ur.UserId
                              where pf.ProfileModelID == profileModelID
                              select new
                              {
                                  Userid = ur.UserId,
                                  Username = ur.UserName,                                 
                              }
                  ;
            var p = userInfo.FirstOrDefault();
            this.UsernameOfPhotoOwner = p.Username;
            this.Photos = db.PhotoModels.Where(x => x.UserID == p.Userid).ToList();
            ProfileModelID = profileModelID;
        }
    }
}

Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LadiesChoice.Models;
using LadiesChoice.Utilities;
using LadiesChoice.ViewModels;
using System.IO;
using System.Web.Security;
using AutoMapper;
using WebMatrix.WebData;
using LadiesChoice.Filters;
using System.Configuration;
using System.Web.Helpers;
using System.Drawing.Imaging;

namespace LadiesChoice.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class PhotoController : Controller
    {
        private DBEntities db = new DBEntities();

        //
        // GET: /Photo/

        public ActionResult ViewPhotos(Guid profileModelID, string flashMessage = null) {
            if (!WebSecurity.HasUserId) { return RedirectToAction("Login", "Account", new { returnURL = "/Photo/ViewPhotos/" + profileModelID }); }

            ProfileModel profilemodel = db.ProfileModels.FirstOrDefault(x => x.ProfileModelID == profileModelID);
            if (profilemodel == null)
            {
                return HttpNotFound();
            }
            if (profilemodel.iUserID == WebSecurity.CurrentUserId)
            { //check if the user is trying to view their own profile
                return RedirectToAction("MyPhotos");
            }

            if (db.BlockedUserModels.Count(y => y.BlockeeUserID == WebSecurity.CurrentUserId && y.BlockerUserID == profilemodel.iUserID) > 0)
            {
                return RedirectToAction("MyPhotos", new { flashMessage = "Sorry, that user has blocked you." });
            }
            
            var model = new MyPhotosViewModel(profileModelID, db);
            model.Setup(this.HttpContext, WebSecurity.CurrentUserId, WebSecurity.CurrentUserName, db);
            model.FlashMessage = flashMessage;
            return View(model);
        }
        
        public ActionResult MyPhotos(string flashMessage=null)
        {
            if (!WebSecurity.HasUserId) { return RedirectToAction("Login", "Account", new { returnURL = "/Photo/MyPhotos/"}); }

            var model = new MyPhotosViewModel();
            UserProfile u = db.UserProfiles.FirstOrDefault(y => y.UserId == WebSecurity.CurrentUserId);
            //model.Setup(this.HttpContext, WebSecurity.CurrentUserId, WebSecurity.CurrentUserName, db, u.HasUploadedPhoto);
            model.Setup(this.HttpContext, WebSecurity.CurrentUserId, WebSecurity.CurrentUserName, db);
            model.FlashMessage = flashMessage;

            var g = WebSecurity.CurrentUserId;
            model.Photos = db.PhotoModels.Where(x => x.UserID == g ).ToList();
            model.IsIPhoneOrIpad = MobileDetectionSupport.IsMobileDevice(Request.UserAgent);
            return View(model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult MyPhotos(MyPhotosViewModel model)
        {

            if (ModelState.IsValid)
            {
                Mapper.CreateMap<MyPhotosViewModel, PhotoModel>();
                PhotoModel photomodel = Mapper.Map<MyPhotosViewModel, PhotoModel>(model);

          
                var g = WebSecurity.CurrentUserId;

                photomodel.UserID = g; //set the userID otherwise it gets overwritten

                photomodel.PhotoModelID = Guid.NewGuid();
                PhotoModel p = db.PhotoModels.FirstOrDefault(x => x.UserID == g && x.IsMainPhoto==true);
                if (p == null)
                {
                    photomodel.IsMainPhoto = true;
                }
                db.PhotoModels.Add(photomodel);

                UserProfile u = db.UserProfiles.FirstOrDefault(y => y.UserId == g);
                u.HasUploadedPhoto = true;

                LadiesChoice.Utilities.ImageProcessing.resizeImage(model.File, photomodel.PhotoModelID.ToString() + ".jpg");
                db.SaveChanges();
                return RedirectToAction("MyPhotos", new { flashMessage = "Photo Uploaded." });
            }

            return View(model);
        }

        public ActionResult Editor() {
            return RedirectToAction("MyPhotos");
        }


        [HttpPost]
        public ActionResult Editor(MyPhotosViewModel model)
        {
            if (!WebSecurity.HasUserId) { return RedirectToAction("Login", "Account", new { returnURL = "/Photo/MyPhotos/" }); }
            
            var image = WebImage.GetImageFromRequest();
            if (image != null)
            {
                if (image.Width > 640)
                {
                    image.Resize(640, ((640 * image.Height) / image.Width));
                }
                Guid photoModelID = Guid.NewGuid();
                string filename = photoModelID.ToString() + ".jpg";

                

                image.Save(Path.Combine("~/Images", filename), ImageFormat.Jpeg.ToString());
                filename = Path.Combine("~/Images", filename);

                TagLib.File file = null;

                file = TagLib.File.Create(System.Web.HttpContext.Current.Server.MapPath(filename));
            
                var image7 = file as TagLib.Image.File;
                image7.RemoveTags(TagLib.TagTypes.AllTags);
                try
                {
                    image7.Save();
                }
                catch(Exception) {}
                double topCrop;
                double leftCrop;
                double rightCrop;
                double bottomCrop;
                double deltaCrop;
                if (image.Width > image.Height)
                {
                    deltaCrop = (image.Width - image.Height) / 2;
                    topCrop = deltaCrop;
                    leftCrop = 0;
                    rightCrop = image.Width - deltaCrop;
                    bottomCrop = image.Height;
                }
                else
                {
                    deltaCrop = (image.Height - image.Width) / 2;
                    topCrop = 0;
                    leftCrop = deltaCrop;
                    rightCrop = image.Width;
                    bottomCrop = image.Height - deltaCrop;
                }
                var editModel = new PhotoEditorViewModel()
                {
                    ImageUrl = Url.Content(filename),
                    PhotoModelID = photoModelID,
                    Width = image.Width,
                    Height = image.Height,
                    //Top = image.Height * 0.1,
                    //Left = image.Width * 0.9,
                    //Right = image.Width * 0.9,
                    //Bottom = image.Height * 0.9
                    Top = topCrop,
                    Left = leftCrop,
                    Right = rightCrop,
                    Bottom = bottomCrop,
                    IntialPageLoad = true
                };
                //UserProfile u = db.UserProfiles.FirstOrDefault(y => y.UserId == WebSecurity.CurrentUserId);

                //editModel.Setup(this.HttpContext, WebSecurity.CurrentUserId, WebSecurity.CurrentUserName, db, u.HasUploadedPhoto);
                editModel.Setup(this.HttpContext, WebSecurity.CurrentUserId, WebSecurity.CurrentUserName, db);
                //editModel.FlashMessage = "orientation" + image7.ImageTag.Orientation;
                return View("Editor", editModel);

            }

            return RedirectToAction("MyPhotos", new { flashMessage = "There was an issue uploading your photo, please try again." });
        }

        public ActionResult EditorOutput(PhotoEditorViewModel editor)
        {

            var image = new WebImage("~" + editor.ImageUrl);

            
            var height = image.Height;
            var width = image.Width;
            int cropHeight;
            int cropWidth;
            int cropTop;
            int cropLeft;
            if (editor.NoEditor)
            {
                if (width > height)
                {
                    cropWidth = (width - height) / 2;
                    cropHeight = 0;
                    cropTop = 0;
                    cropLeft = (width - height) / 2; 
                }
                else
                {
                    cropWidth = 0;
                    cropHeight = (height - width) / 2;
                    cropTop = (height - width) /2;
                    cropLeft = 0;
                }
                                
            }
            else
            {
                cropHeight = (int)(height - editor.Bottom + 1);
                cropWidth = (int)(width - editor.Right);
                if (cropHeight < 0) { cropHeight = 0; }
                if (cropWidth < 0) { cropWidth = 0; }
                cropTop = (int)editor.Top;
                cropLeft = (int)editor.Left;
                image.Crop(cropTop, cropLeft, cropHeight, cropWidth);
            }
            
            //image.Crop(cropTop, cropLeft, cropHeight, cropWidth);
            var originalFile = editor.ImageUrl;

            PhotoModel photomodel = new PhotoModel();
            photomodel.PhotoModelID = Guid.NewGuid();

            string FileNameOnly = photomodel.PhotoModelID + ".jpg";
            string tempFileName = Path.GetFileName(image.FileName);
            editor.ImageUrl = Url.Content("~/App_Data/uploads/main_" + FileNameOnly);
            //image.Save(@"~" + editor.ImageUrl);
            image.Save();

    
            AWSFunctions awsf = new AWSFunctions();
            string serverPath = System.Web.HttpContext.Current.Server.MapPath("/Images/" + tempFileName);

            awsf.UploadFile(serverPath, "main/" + FileNameOnly);

            if (editor.NoEditor) //we leave the main image uncropped if no crop tool was used; this crops the image in prep for thumbnail which must be cropped
            {
                image.Crop(cropTop, cropLeft, cropHeight, cropWidth);
            }
            image.Resize(150, 150);
            image.Save();
            awsf.UploadFile(serverPath, "thumb/" + FileNameOnly);

            var g = WebSecurity.CurrentUserId;

Views/Photo/Create.cshtml
@model LadiesChoice.Models.PhotoModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>PhotoModel</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserID)
            @Html.ValidationMessageFor(model => model.UserID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Caption)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Caption)
            @Html.ValidationMessageFor(model => model.Caption)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsMainPhoto)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsMainPhoto)
            @Html.ValidationMessageFor(model => model.IsMainPhoto)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Photo/Delete.cshtml
@model LadiesChoice.Models.PhotoModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>PhotoModel</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Caption)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Caption)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IsMainPhoto)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsMainPhoto)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Views/Photo/Details.cshtml
@model LadiesChoice.Models.PhotoModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>PhotoModel</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Caption)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Caption)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IsMainPhoto)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsMainPhoto)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.PhotoModelID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Photo/Edit.cshtml
@model LadiesChoice.Models.PhotoModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>PhotoModel</legend>

        @Html.HiddenFor(model => model.PhotoModelID)

        <div class="editor-label">
            @Html.LabelFor(model => model.UserID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserID)
            @Html.ValidationMessageFor(model => model.UserID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Caption)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Caption)
            @Html.ValidationMessageFor(model => model.Caption)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsMainPhoto)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsMainPhoto)
            @Html.ValidationMessageFor(model => model.IsMainPhoto)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Photo/Editor.cshtml
@model LadiesChoice.ViewModels.PhotoEditorViewModel

     <link href="@Url.Content("~/Content/jquery.Jcrop.css")" rel="stylesheet" type="text/css" />

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
     



<h1>Edit your photo</h1> 
 <div id="mainform">
 @using (Html.BeginForm("EditorOutput", "Photo", FormMethod.Post))
 {
       <div class="photoEditBtns">
         <div class="photoRoBtn">
             <input type='button' id="rotatebtnleft" name="rotatebtnleft" value='' class="btn" />
             <input type='button' id="rotatebtnright" name="rotatebtnright" value='' class="btn" />
         </div>
         <input type='submit' name='action' value='Save photo' class="btn btn-success" />
     </div> 
     <div id="photoEdit">
     @Html.Partial("_photoEditor", Model)
         </div>    
      @Html.HiddenFor(x => x.Left)
      @Html.HiddenFor(x => x.Right)
      @Html.HiddenFor(x => x.Top)
      @Html.HiddenFor(x => x.Bottom)
      @Html.HiddenFor(x => x.ImageUrl)
      @Html.Hidden("NoEditor", true);
 }

</div>

 
    <script type="text/javascript" defer="defer">
        $(document).ready(function () {
            $('#rotatebtnleft').on('click', function () {
                var d = new Date();
                var strMethodUrl = '@Url.Action("Rotate", "Photo")/@Model.PhotoModelID?clockWise=false&dt=' + d.getTime();
                $.get(strMethodUrl, function(data) {
                    $('#photoEdit').html(data);
                });
             });
                
                $(document).on("click","#rotatebtnright",function(){
                    var d = new Date();
                    var strMethodUrl = '@Url.Action("Rotate", "Photo")/@Model.PhotoModelID?dt=' + d.getTime();
                      $.get(strMethodUrl, function(data) {
                          $('#photoEdit').html(data);
                      });
                });   
          
        
        
         });
        </script>
      <script src="/Scripts/lcv.js" type="text/javascript" defer="defer"></script>

 <script src="@Url.Content("~/Scripts/jquery.Jcrop.js")" type="text/javascript" defer="defer"></script>

Views/Photo/Index.cshtml
@model IEnumerable<LadiesChoice.Models.PhotoModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Caption)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsMainPhoto)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Caption)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsMainPhoto)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PhotoModelID }) |
            @Html.ActionLink("Details", "Details", new { id=item.PhotoModelID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PhotoModelID })
        </td>
    </tr>
}

</table>

Views/Photo/MyPhotos.cshtml
@model LadiesChoice.ViewModels.MyPhotosViewModel

@{
    ViewBag.Title = "My Photos";
}

@using (Html.BeginForm("Editor", "Photo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    
    if (Model.ShowMenu)
    {
        <h1>My Photos</h1>
    }
    else
    {
        
        <h1>Add some photos</h1>
        if (!Model.IsFemale) {
        <p>Having a photo will increase your chances of being contacted exponentially.  Having multiple photos is even better. </p>
        }
    }

        <fieldset>
            @if (Model.ShowMenu)
            { <legend>Add a photo</legend> }
            <div><input type="file" name="File" class="photo-fileupld"> 
            <input type="submit" value="Post Photo" class ="btn btn-success" onclick="$('#PleaseWait').show();" >
						
                    
					<img id='PleaseWait' style='display: none;' src='/Content/images/spinner.gif'/>
            @Html.ValidationMessageFor(model => model.File)
                </div>
        </fieldset>
    
    
    @*
    
    
    @{
    @Scripts.Render("~/bundles/jquery")
    <script src="@Url.Content("~/Scripts/JCrop/jquery.Jcrop.js")" type="text/javascript"></script>
    <link rel="stylesheet" href="@Url.Content("~/Content/JCrop/jquery.Jcrop.css")" type="text/css" />
}

    @{
    ViewBag.Title = "Avatar Editor Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model SimsTemplate.Models.ViewModels.AvatarEditorModel

<script type="text/javascript">

    $(function() {
     jQuery('#avatarImageEditor').Jcrop({
        onChange: showPreview,
        onSelect: showPreview,
        setSelect: [@Model.Top, @Model.Left, @Model.Right, @Model.Bottom],
        aspectRatio: 1
    });
 });

function showPreview(coords)  {
     if (parseInt(coords.w) > 0)  {
         $('#Top').val(coords.y);
         $('#Left').val(coords.x);
         $('#Bottom').val(coords.y2);
         $('#Right').val(coords.x2);

         var width = @Model.Width;
         var height = @Model.Height;
         var rx = 100 / coords.w;
         var ry = 100 / coords.h;

         jQuery('#preview').css({
             width: Math.round(rx * width) + 'px',
             height: Math.round(ry * height) + 'px',
             marginLeft: '-' + Math.round(rx * coords.x) + 'px',
             marginTop: '-' + Math.round(ry * coords.y) + 'px'
         });
     }
}

</script>

 <div id="cropContainer">

     <div id="cropPreview">
     Preview:
        <img src="@Model.Avatar.ImageUrl" id="preview" alt="" />
    </div>

 <div id="cropDisplay">
 Display:
     <img src="/Content/image/strawberry.png" id="avatarImageEditor" alt="" />
</div>

<input id="Top" name="Top" type ="text"/>
<input id="Bottom" name="Top" type ="text"/>
<input id="Left" name="Top" type ="text"/>
<input id="Right" name="Top" type ="text"/>

</div>

<div id="mainform">

@using (Html.BeginForm("Edit", "Avatar", FormMethod.Post))
{
    @Html.DisplayFor(x => x.Avatar.ImageUrl)         
    @Html.HiddenFor(x => x.Left)
    @Html.HiddenFor(x => x.Right)
    @Html.HiddenFor(x => x.Top)
    @Html.HiddenFor(x => x.Bottom)
    @Html.HiddenFor(x => x.Avatar.ImageUrl)
    <input type='submit' name='action' value='Crop' />
}
</div>    
    
 *@  
}
@if (Model.IsIPhoneOrIpad)
{ <p>Note: For iPhones and iPads you must have iOS 6 or greater to upload photos.</p><br /> }


@if (Model.Photos != null)
{
    if (Model.Photos.Count() > 0)
    {
            @*<h1>Pictures of Me</h1>*@
    }
    else
    {
        if (!Model.IsFemale)
        {
            <p><strong>Having a photo will increase your chances of being contacted exponentially.  Having multiple photos is even better.</strong></p>
        }
    }
    foreach (var photo in Model.Photos)
    {
     <div class="photowell">
         <div>
           <img src="@Url.Content(Model.PhotoPath + "main/" + photo.PhotoModelID.ToString() + ".jpg")">
             @if (photo.Caption != null) {<p>@photo.Caption</p> }
         </div>
         <br />
         <div>
             <div class="photo-btn">
         @using (Html.BeginForm("Caption", "Photo", new { id = photo.PhotoModelID }, FormMethod.Post))
         {
             @Html.AntiForgeryToken()
             @Html.TextBox("caption", photo.Caption)
                 @*<input type="text" name="caption">@Html.DisplayFor(model => photo.Caption)>*@
           
             <input type="submit" value="Update Caption" class="btn btn-primary photo-caption-btn">
         }
                 </div>
         <div class="photo-btn">
         @using (Html.BeginForm("Promote", "Photo", new { id = photo.PhotoModelID }, FormMethod.Post))
         {
             @Html.AntiForgeryToken()
             <input type="submit" class="btn btn-warning" value="Set Profile Picture">
         }
             </div>
            <div class="photo-btn">
         @using (Html.BeginForm("DeleteConfirmed", "Photo", new { id = photo.PhotoModelID }, FormMethod.Post))
         {
             @Html.AntiForgeryToken()
             <input type="submit" class="btn btn-danger" value="Delete">
         }
                </div>
         </div>
     </div>          
 }
}
      <script src="/Scripts/lcv.js" type="text/javascript" defer="defer"></script>


@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

Views/Photo/MyPhotos_bak.cshtml
@model LadiesChoice.ViewModels.MyPhotosViewModel

@{
    ViewBag.Title = "My Photos";
}

@using (Html.BeginForm("MyPhotos", "Photo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    if (Model.ShowMenu)
    {
        <h1>My Photos</h1>
    }
    else
    {
        <h1>Add some photos</h1>
    @if (!Model.IsFemale) {
    <p>Having a photo will increase your chances of being contacted exponentially.  Having multiple photos is even better. </p>
    }
    }

        <fieldset>
            @if (Model.ShowMenu) { <legend>Add a photo</legend> }
            <div><input type="file" name="File" class="photo-fileupld"> 
            <input type="submit" value="Post Photo" class ="btn btn-success">
            @Html.ValidationMessageFor(model => model.File)
                </div>
        </fieldset>
   
}
@if (Model.IsIPhoneOrIpad) { <p>Note: For iPhones and iPads you must have iOS 6 or greater to upload photos.</p><br /> }


@if (Model.Photos != null) {
        if (Model.Photos.Count() > 0) {
            @*<h1>Pictures of Me</h1>*@
        } else { 
            if (!Model.IsFemale) {
            <p><strong>Your profile will not be visible to ladies until you add a picture of yourself.</strong></p>
            }
        }
 foreach (var photo in Model.Photos) {
     <div class="photowell">
         <div>
           <img src="@Url.Content(Model.PhotoPath + "main/" + photo.PhotoModelID.ToString()+ ".jpg")">
         </div>
         <br />
         <div>
             <div class="photo-btn">
         @using (Html.BeginForm("Caption", "Photo", new { id = photo.PhotoModelID }, FormMethod.Post))
         {
             @Html.AntiForgeryToken()
             @Html.TextBox("caption", photo.Caption)
                 @*<input type="text" name="caption">@Html.DisplayFor(model => photo.Caption)>*@
           
             <input type="submit" value="Update Caption" class="btn btn-primary photo-caption-btn">
         }
                 </div>
         <div class="photo-btn">
         @using (Html.BeginForm("Promote", "Photo", new { id=photo.PhotoModelID }, FormMethod.Post))
         {
             @Html.AntiForgeryToken()
             <input type="submit" class="btn btn-warning" value="Set Profile Picture">
         }
             </div>
            <div class="photo-btn">
         @using (Html.BeginForm("DeleteConfirmed", "Photo", new { id = photo.PhotoModelID }, FormMethod.Post))
         {
             @Html.AntiForgeryToken()
             <input type="submit" class="btn btn-danger" value="Delete">
         }
                </div>
         </div>
     </div>          
 }
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Photo/ViewPhotos.cshtml
@model LadiesChoice.ViewModels.MyPhotosViewModel

@{
    ViewBag.Title = "View Photos";
}

    <h1>Pictures of @Model.UsernameOfPhotoOwner</h1>
<p><a href="/Profile/Index/@Model.ProfileModelID">Back to @Model.UsernameOfPhotoOwner's profile</p></a>

 @foreach (var photo in Model.Photos) {
     <div class="photowell">
         <div>
           <img src="@Url.Content(Model.PhotoPath + "main/" + photo.PhotoModelID.ToString()+ ".jpg")">
         </div>
         <div>@photo.Caption</div>
         <div><a href="/Photo/Report/@Model.ProfileModelID/?photo=@photo.PhotoModelID">report</a></div>
         <br />
         
     </div>          
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}